# -*- coding: utf-8 -*-
"""Data_Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6AZpFc2KjzrhV8R0mDJmeA4i8WLtTzU
"""

# Author - Elijah Stenberg
# Personal project exploring Python capabilities in data science context
# October 2025
!pip install tweepy pandas matplotlib textblob

import tweepy
import pandas as pd
import matplotlib.pyplot as plt
from textblob import TextBlob

from google.colab import userdata
import os

# Credential set up
try:
    bearer_token = userdata.get("BEARER_TOKEN")  # v2 only

    if not bearer_token:
        print("Error: Bearer Token not found in Colab Secrets Manager.")
        print("Set BEARER_TOKEN in the Secrets Manager")
    else:
        # Tweepy v2 Client
        client = tweepy.Client(bearer_token=bearer_token)

        # Collect a small sample of live tweets (v2 API)
        query = "the -is:retweet lang:en"  # sample English tweets, no retweets
        tweets = client.search_recent_tweets(
        query=query,
        max_results=25,
        tweet_fields=["created_at","text","public_metrics"]
)

        # Store tweets
        data = []
        if tweets.data:
            for t in tweets.data:
                data.append({
                    "date": t.created_at,
                    "text": t.text,
                    "likes": t.public_metrics.get("like_count",0),
                    "retweets": t.public_metrics.get("retweet_count",0)
                })
            df = pd.DataFrame(data)
            print("Sample tweets:")
            display(df.head())

            # Sentiment Analysis
            df["sentiment"] = df["text"].apply(lambda x: TextBlob(x).sentiment.polarity)
            df["label"] = df["sentiment"].apply(lambda x: "Positive" if x>0.05 else ("Negative" if x<-0.05 else "Neutral"))
            print("Sentiment Analysis Results:")
            display(df[["text", "sentiment", "label"]].head())

            # Visualization
            # Sentiment distribution
            plt.figure(figsize=(6,4))
            df["label"].value_counts().plot(kind="bar", color=["green","gray","red"])
            plt.title("Sentiment Distribution of Sampled Tweets")
            plt.xlabel("Sentiment")
            plt.ylabel("Number of Tweets")
            plt.show()

            # Likes vs sentiment scatter
            plt.figure(figsize=(6,4))
            plt.scatter(df["sentiment"], df["likes"])
            plt.title("Likes vs Sentiment for Sampled Tweets")
            plt.xlabel("Sentiment")
            plt.ylabel("Likes")
            plt.show()
        else:
            print("No tweets returned in this sample. Adjust the query.")

except tweepy.errors.TweepyException as e:
    print(f"Error fetching tweets: {e}")
except Exception as e:
    print(f"Unexpected error: {e}")

import os

print("Environment Variables:")
for key, value in os.environ.items():
    # Print only a few to avoid clutter, or filter if you know a variable name that should exist
    # For example, print only variables containing 'COLAB' or 'KEY'
    if 'COLAB' in key or 'KEY' in key:
         print(f"{key}: {value}")
    # To print all environment variables, uncomment the line below:
    # print(f"{key}: {value}")